project_id = "mxatgocmnasozbkbjiuq"

[functions.ai-recommendations]
verify_jwt = true

[functions.drive-proxy]
verify_jwt = false

[functions.media-proxy]
verify_jwt = false

[functions.youtube-api]
verify_jwt = false

[functions.vimeo-oembed]
verify_jwt = false
